/* PEFPercentPred*/
filename rf "/home/wwang750/Biofluc_testRVeffectiveness_cytokine/mrm_PEFPercentPred.csv";
proc import datafile=rf
        out=PEFPercentPred
        dbms=csv
        replace;
        run;
        
data PEFPercentPred;
set PEFPercentPred ;
LINEAR = TIME;
logPEFPercentPred = log(PEFPercentPred);
run;

PROC FORMAT;
VALUE GROUP 0='Healthy' 1='Asthmatic';
/* VALUE Time 1='Day 1' 2='Day 3' 3='Day 6' 4='Day 8' 5='Day 10'; */

        
* spaghetti, regression, and spline plots;
TITLE 'Observed Data, All Subjects';
PROC SGPLOT NOAUTOLEGEND DATA=PEFPercentPred;
	* observed trends;
	SERIES X=TIME Y=logPEFPercentPred / GROUP=ID LINEATTRS=(THICKNESS=1);
	*overall linear ;
	REG X=TIME Y=logPEFPercentPred / NOMARKERS LINEATTRS=(COLOR=BLUE PATTERN=1 THICKNESS=3);
	*overall spline;
	PBSPLINE X=TIME Y=logPEFPercentPred / NOMARKERS LINEATTRS=(COLOR=RED THICKNESS=3);
RUN;


/* PART 1 */
PROC MEANS DATA=PEFPercentPred NWAY MEAN STD;
	CLASS TIME;
	VAR logPEFPercentPred;
RUN;

/* ***************************************************** */
/* some random effects models with autocorrelated errors */
/* ***************************************************** */
/* TIME  GROUP GROUP*TIME */

PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT /SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID R RCORR; 

PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT /SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=AR(1) R RCORR; 
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT /SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=ARH(1) R RCORR; 
		
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT /SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=ARMA(1,1) R RCORR; 
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT /SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(2) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT /SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(3) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT /SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(4) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID R RCORR; 

PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=AR(1) R RCORR; 
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=ARH(1) R RCORR; 
		
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=ARMA(1,1) R RCORR; 
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(2) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(3) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(4) R RCORR;	
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME TIME*TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID R RCORR; 

PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME TIME*TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=AR(1) R RCORR; 
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME TIME*TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=ARH(1) R RCORR; 
		
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME TIME*TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=ARMA(1,1) R RCORR; 
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME TIME*TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(2) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME TIME*TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(3) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	RANDOM INTERCEPT TIME TIME*TIME/SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(4) R RCORR;

/*  */
/* ******************************** */
/* some covariance structure models */
/* ******************************** */
/*  */
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	REPEATED LINEAR /SUB=ID TYPE=CS R RCORR; 
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	REPEATED LINEAR /SUB=ID TYPE=AR(1) R RCORR;

PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	REPEATED LINEAR /SUB=ID TYPE=ARH(1) R RCORR;

PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	REPEATED LINEAR /SUB=ID TYPE=ARMA(1,1) R RCORR;

PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(2) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(3) R RCORR;
	
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(4) R RCORR;
	
	
/* Unstructured, saturated model	 */
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S;
	REPEATED LINEAR /SUB=ID TYPE=UN R RCORR;
	
	
/* 	Final model */
PROC MIXED METHOD=ML COVTEST;
	CLASS ID LINEAR;
	MODEL logPEFPercentPred=TIME GROUP GROUP*TIME/S outp=pred;
	RANDOM INTERCEPT /SUB=ID TYPE=UN G GCORR;
	REPEATED LINEAR /SUB=ID TYPE=TOEP(3) R RCORR;

/* Proc export */
/* DATA =work.pred */
/* DBMS=xlsx */
/* outfile="/home/wwang750/Biofluc_testRVeffectiveness_cytokine/Output/PEFpercentpred_individual.xlsx" REPLACE;  */
/* RUN; */
